### ISSUE TITLE
設定の同期をONにした状態で時間割に登録できない科目が生まれてしまうことがある。

### ISSUE THREAD

**Issue by hotman78** [mkihr-ojisan/better-waseda-moodle#1]
# 概要
設定の同期をONにした状態で時間割に登録できない科目が生まれてしまうことがある。

# 再現手順
- (恐らく)沢山の科目を履修登録する。
- 設定の同期をONにする
- 時間割とシラバスのURLを取得する

こちらの手順で行ったところ一部の科目が登録されませんでした。
また、この状態で登録されなかった科目に時間割を設定した際、時間割の設定はされたもののターミナルにて

```
Uncaught (in promise) Error: QUOTA_BYTES_PER_ITEM quota exceeded
```
というエラーを吐き、リロードすることで時間割の設定はされてない状態に戻りました。

# 原因
設定の同期をONにした際に拡張機能のストレージ制限に引っかかってしまうことに原因がありそうです。

# 修正案
根本的な修正自体はchrome拡張自体の制限なので難しそうですが、このエラーが出た際の警告文等を作成する等が可能そうです。
また、可能であればストレージに保存するデータの圧縮等でも対処になりそうです。

**Comment by mkihr-ojisan** [comment]
v0.6.0からストレージ圧縮するようにしました
